# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: exchange.proto
# Protobuf Python Version: 7.35.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    0,
    '',
    'exchange.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x65xchange.proto\x12\x08\x65xchange\"F\n\x11\x43omplianceRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x0e\n\x06\x61mount\x18\x02 \x01(\x01\x12\x10\n\x08\x63urrency\x18\x03 \x01(\t\"7\n\x12\x43omplianceResponse\x12\x10\n\x08\x61pproved\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"^\n\x11SettlementRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x0e\n\x06\x61mount\x18\x02 \x01(\x01\x12\x10\n\x08\x63urrency\x18\x03 \x01(\t\x12\x16\n\x0etransaction_id\x18\x04 \x01(\t\"V\n\x12SettlementResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x16\n\x0etransaction_id\x18\x02 \x01(\t\x12\x17\n\x0f\x63urrent_balance\x18\x03 \x01(\x01\x32\x63\n\x11\x43omplianceService\x12N\n\x11\x43heckDepositLimit\x12\x1b.exchange.ComplianceRequest\x1a\x1c.exchange.ComplianceResponse2c\n\x11SettlementService\x12N\n\x11ProcessSettlement\x12\x1b.exchange.SettlementRequest\x1a\x1c.exchange.SettlementResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'exchange_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_COMPLIANCEREQUEST']._serialized_start=28
  _globals['_COMPLIANCEREQUEST']._serialized_end=98
  _globals['_COMPLIANCERESPONSE']._serialized_start=100
  _globals['_COMPLIANCERESPONSE']._serialized_end=155
  _globals['_SETTLEMENTREQUEST']._serialized_start=157
  _globals['_SETTLEMENTREQUEST']._serialized_end=251
  _globals['_SETTLEMENTRESPONSE']._serialized_start=253
  _globals['_SETTLEMENTRESPONSE']._serialized_end=339
  _globals['_COMPLIANCESERVICE']._serialized_start=341
  _globals['_COMPLIANCESERVICE']._serialized_end=440
  _globals['_SETTLEMENTSERVICE']._serialized_start=442
  _globals['_SETTLEMENTSERVICE']._serialized_end=541
# @@protoc_insertion_point(module_scope)
