# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import exchange_pb2 as exchange__pb2

GRPC_GENERATED_VERSION = '1.82.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in exchange_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ComplianceServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CheckDepositLimit = channel.unary_unary(
                '/exchange.ComplianceService/CheckDepositLimit',
                request_serializer=exchange__pb2.ComplianceRequest.SerializeToString,
                response_deserializer=exchange__pb2.ComplianceResponse.FromString,
                _registered_method=True)


class ComplianceServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def CheckDepositLimit(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ComplianceServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CheckDepositLimit': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckDepositLimit,
                    request_deserializer=exchange__pb2.ComplianceRequest.FromString,
                    response_serializer=exchange__pb2.ComplianceResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'exchange.ComplianceService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('exchange.ComplianceService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ComplianceService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CheckDepositLimit(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/exchange.ComplianceService/CheckDepositLimit',
            exchange__pb2.ComplianceRequest.SerializeToString,
            exchange__pb2.ComplianceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class SettlementServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ProcessSettlement = channel.unary_unary(
                '/exchange.SettlementService/ProcessSettlement',
                request_serializer=exchange__pb2.SettlementRequest.SerializeToString,
                response_deserializer=exchange__pb2.SettlementResponse.FromString,
                _registered_method=True)


class SettlementServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def ProcessSettlement(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SettlementServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ProcessSettlement': grpc.unary_unary_rpc_method_handler(
                    servicer.ProcessSettlement,
                    request_deserializer=exchange__pb2.SettlementRequest.FromString,
                    response_serializer=exchange__pb2.SettlementResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'exchange.SettlementService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('exchange.SettlementService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SettlementService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ProcessSettlement(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/exchange.SettlementService/ProcessSettlement',
            exchange__pb2.SettlementRequest.SerializeToString,
            exchange__pb2.SettlementResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
